[workspace]
members = [
   "crates/cachet-lang",
   "crates/cachet-compiler",
   "crates/stub-verifier",
]


# LALRPOP is really slow when built as debug, so let's just always opt it
[profile.dev.package.lalrpop]
opt-level=3