[package]
name = "cachet-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cachet-lang = {path="../cachet-lang"}
iterate = "1.0.0"
indent_write = "2.2.0"
codespan-reporting = "0.11.1"
anyhow = "1.0.28"
structopt = "0.3.22"
derive_more = "0.99.16"
typed-index-collections = "3.0.3"
lazy_static = "1.4.0"
